-- Seed de productos (portado desde data/productos.json + js/productos.js)
insert into public.productos (id, nombre, descripcion, precio, stock, stock_critico, categoria, imagen, busqueda, destacado, especificaciones)
values
('rtx3080', 'RTX 3080', 'Tarjeta de video NVIDIA RTX 3080, gran rendimiento para gaming en 1440p y 4K.', 409990, 10, 2, 'componentes', '/img/rtx3080.jpg', 'rtx 3080 nvidia tarjeta grafica', '{"titulo": "Rendimiento Extremo", "texto": "Si buscas lo mejor, esta gráfica es para ti. Rendimiento ideal para jugar a máximos ajustes, altas tasas de FPS y tareas de renderizado profesional."}'::jsonb, '{"Fabricante": "NVIDIA", "Categoría": "Tarjeta gráfica", "Card Bus": "PCI-E 4.0", "Garantía": "12 meses"}'::jsonb),
('monitorZowie', 'Monitor Zowie', 'Monitor gamer BenQ Zowie de alta frecuencia de actualización, pensado para esports.', 1590990, 6, 2, 'perifericos', '/img/monitor.jpg', 'monitor zowie benq gamer', '{"titulo": "Ventaja Competitiva", "texto": "Cada milisegundo cuenta. Diseñado específicamente para eSports con tecnología DyAc para una claridad de movimiento inigualable."}'::jsonb, '{"Fabricante": "BenQ Zowie", "Categoría": "Monitor gamer", "Garantía": "12 meses"}'::jsonb),
('switch2', 'Switch 2 256GB', 'Consola híbrida Nintendo Switch 2, con 256GB de almacenamiento interno.', 556990, 15, 3, 'consolas', '/img/switch2.avif', 'switch 2 256gb nintendo consolas', '{"titulo": "Nueva Generación", "texto": "Lleva tus juegos favoritos a cualquier parte con gráficos mejorados, mayor duración de batería y una pantalla vibrante."}'::jsonb, '{"Fabricante": "Nintendo", "Categoría": "Consola", "Almacenamiento": "256GB", "Garantía": "12 meses"}'::jsonb),
('notebookLegion', 'Notebook Gamer Legion', 'Notebook gamer Lenovo Legion, pensado para gaming y trabajo exigente.', 1290990, 5, 2, 'consolas', '/img/notebookGamer.webp', 'notebook gamer legion lenovo laptop', '{"titulo": "Potencia Portátil", "texto": "El equilibrio perfecto entre rendimiento térmico y potencia bruta. Todo el poder de un PC de escritorio en tu mochila."}'::jsonb, '{"Fabricante": "Lenovo", "Categoría": "Notebook gamer", "Garantía": "12 meses"}'::jsonb),
('ryzen7', 'Procesador Ryzen 7', 'Procesador AMD Ryzen 7, gran rendimiento multi-hilo para gaming y multitarea.', 346990, 12, 3, 'componentes', '/img/proceRyzen7.jpg', 'procesador ryzen 7 amd cpu', '{"titulo": "Multitarea sin Límites", "texto": "Arquitectura de última generación para exprimir tus juegos y ejecutar aplicaciones pesadas simultáneamente sin caídas de rendimiento."}'::jsonb, '{"Fabricante": "AMD", "Categoría": "Procesador", "Socket": "AM5", "Garantía": "12 meses"}'::jsonb),
('refCorsair', 'Refrigeracion Liquida Corsair', 'Sistema de refrigeración líquida Corsair para mantener tu CPU a bajas temperaturas.', 250990, 8, 2, 'componentes', '/img/refrigeracionLiquida.jpg', 'refrigeracion liquida corsair', '{"titulo": "Temperaturas a Raya", "texto": "Disipación térmica superior con un toque estético inigualable. Mantén tu equipo frío incluso en las sesiones de juego más exigentes."}'::jsonb, '{"Fabricante": "Corsair", "Categoría": "Refrigeración líquida", "Garantía": "12 meses"}'::jsonb),
('tecladoProX60', 'Teclado Logitech PRO X60', 'Teclado mecánico gamer Logitech PRO X60, compacto e inalámbrico.', 189990, 20, 4, 'perifericos', '/img/tecladoLogitech.png', 'teclado logitech pro x60', '{"titulo": "Diseño Compacto", "texto": "Libera espacio en tu escritorio sin sacrificar funcionalidad. Switches mecánicos ultra rápidos ideales para torneos profesionales."}'::jsonb, '{"Fabricante": "Logitech", "Categoría": "Teclado gamer", "Conectividad": "Inalámbrico", "Garantía": "12 meses"}'::jsonb),
('superlight2', 'Logitech Superlight 2', 'Mouse gamer ultraliviano Logitech Superlight 2, ideal para esports.', 245990, 18, 4, 'perifericos', '/img/mouse logitech.jpg', 'mouse logitech superlight 2', '{"titulo": "Precisión Absoluta", "texto": "Equipado con el sensor HERO 2 y un peso que casi no se siente en la mano, permitiendo que tus movimientos fluyan sin resistencia."}'::jsonb, '{"Fabricante": "Logitech", "Categoría": "Mouse gamer", "Conectividad": "Inalámbrico", "Garantía": "12 meses"}'::jsonb),
('audifonosRazer', 'Audifonos Razer Gengar', 'Audífonos gamer Razer edición Gengar, sonido envolvente y micrófono integrado.', 282990, 14, 3, 'perifericos', '/img/audifonosRazer.jpg', 'audifonos razer gengar', '{"titulo": "Audio Inmersivo", "texto": "Siente cada paso del enemigo con audio espacial 7.1, luciendo un diseño exclusivo de edición limitada que no pasará desapercibido."}'::jsonb, '{"Fabricante": "Razer", "Categoría": "Audífonos gamer", "Conectividad": "Inalámbrico", "Garantía": "12 meses"}'::jsonb),
('Nvidia5090', 'Nvidia GeForce 5090', 'Tarjeta de video Nvidia GeForce 5090 32GB VRAM.', 3899990, 3, 1, 'componentes', '/img/rtx.jpg', 'nvidia geforce 5090 rtx tarjeta grafica', '{"titulo": "El Futuro del Gaming", "texto": "Potencia desmesurada para resoluciones 4K, 8K y el máximo aprovechamiento de la inteligencia artificial. La gráfica definitiva."}'::jsonb, '{"Color": "Negro", "Capacidad": "32GB VRAM", "Fabricante": "NVIDIA", "Card Bus": "PCI-E 5.0", "Frecuencia": "3200Mhz", "Procesadores CUDA": "41245", "Tipo de Memoria": "GDDR7", "OpenGL": "4.6", "Puertos de Salida": "Hdmi x 1 DisplayPort x 4", "Puertos de Energía": "1"}'::jsonb);

-- Seed de reseñas (tabla normalizada, referencia a productos)
insert into public.resenas (producto_id, usuario, calificacion, comentario, fecha) values
('rtx3080', 'Carlos M.', 5, 'Rendimiento impecable para 1440p. Muy silenciosa.', '2026-08-10'),
('monitorZowie', 'Matías K.', 5, 'La mejor tasa de refresco para competitivo. 10/10.', '2026-09-02'),
('switch2', 'Ana G.', 4, 'Excelente salto gráfico, la pantalla se ve increíble.', '2026-08-15'),
('switch2', 'Felipe R.', 5, 'Los nuevos joy-cons son mucho más cómodos.', '2026-09-01'),
('notebookLegion', 'Luis P.', 5, 'Corre todo en ultra sin calentarse demasiado.', '2026-07-20'),
('ryzen7', 'Javier V.', 5, 'Potencia bruta para multitarea y gaming.', '2026-09-05'),
('refCorsair', 'Diego R.', 4, 'Mantiene mi CPU bajo los 60 grados jugando. El RGB es hermoso.', '2026-08-12'),
('tecladoProX60', 'Sofía T.', 5, 'Tamaño perfecto para el escritorio y switches súper suaves.', '2026-08-28'),
('superlight2', 'Felipe C.', 5, 'No pesa absolutamente nada y la batería dura semanas.', '2026-09-10'),
('audifonosRazer', 'Camila L.', 5, 'El diseño de Gengar es precioso y el audio espacial funciona genial.', '2026-09-01'),
('Nvidia5090', 'Tomás H.', 5, 'Una verdadera bestia. Asegúrense de tener una buena fuente de poder.', '2026-09-14'),
('Nvidia5090', 'Eduardo S.', 4, 'El precio es altísimo, pero el rendimiento no tiene rival.', '2026-09-16');